version: '3.7'

services:
  fu_db:
    restart: "no"

  fu_web:
    restart: "no"

  fu_nginx:
    restart: "no"
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
